services:
  mariadb: # 伺服器
    image: mariadb:11
    container_name: tire_mariadb
    environment:
      MARIADB_DATABASE: ${DB_NAME} # 資料庫
      MARIADB_USER: ${DB_USERNAME} # 帳號
      MARIADB_PASSWORD: ${DB_PASSWORD} # 密碼
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Taipei
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer: # 資料庫管理介面
    image: adminer:4
    container_name: tire_adminer
    ports:
      - "8081:8080"
    depends_on:
      - mariadb

volumes:
  mariadb_data: # Adminer 要等 mariadb 先啟動

